### ISSUE TITLE
ヒットアンドブローのルール

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/HitAndBlow#1]
- 0～9までの数字4桁を当てるゲーム
- 桁違いの一致は「ブロー」、桁まで一致したら「ヒット」としてカウントする
- 4ヒットでゲームクリア

**Comment by konta3291** [comment]
現在作っております「ヒット＆ブロー」に誠に勝手ながら下記の機能をつけております。
仕様にない機能でしたら削除したいと考えております。ご確認よろしくお願いします。
 - ユーザーから受け取る四桁の整数の中に同じ数字があればもう一度入力していただく
 - ゲームクリア後、アプリを閉じずにもう一度遊べる（終了することもできる）
 以上です。ご確認よろしくお願いします。

**Comment by Takatatsu9** [comment]
質問の形式がよくないですね。
お客様に「勝手に仕様に無い機能作りましたが不要でしたら消して差し上げますよ」と言うのでしょうか？
そこは「～の操作をした場合の挙動はどういたしましょうか？」という形式で聞くべきです。

**Comment by konta3291** [comment]
かしこまりました、書き直します。

**Comment by konta3291** [comment]
お世話になっております。
ヒット＆ブローの仕様についてご確認したいことがあり、ご連絡をしております。
ご確認したい内容は下記の２点です。
 - ユーザから入力された４桁の整数の中で同じ数字が使われていた場合の挙動はどういたしましょうか？
 - ゲームクリア後もう一度遊びたい場合の挙動はどういたしましょうか？（例：アプリを閉じもう一度開く or アプリを閉じずにもう一度遊べるようにする）
 以上です。ご確認よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. 入力する数字に関しては縛らないでください
2. 「もう一度プレイしますか？（Y/N）」と聞くようにお願いします

**Comment by konta3291** [comment]
ご回答ありがとうございます。
「入力する数字に関しては縛らない」とのことですが、下記のものが入力された場合の挙動はどういたしましょうか。
 - 負の数
 - ４桁以降もしくは４桁未満の数字
 - 小数点を含む数字
 - 数字以外の文字
 また、「もう一度プレイしますか？（Y/N）」の質問にユーザーからの入力が「Y」、「N」以外が入力された場合の挙動はどういたしましょうか。
 以上です。
追加のご確認となってしまい申し訳ありません。ご確認よろしくお願いします

**Comment by Takatatsu9** [comment]
1. 負数は数字ではない余計な記号（`-`）が入っていると見做し、エラー
2. ピッタリ4桁では無いならエラー
3. `1.`と同じ理由でエラー
4. `1.`と同じ理由でエラー
5. エラーメッセージなどは出さずに、同じ文言を再度表示する

こんな感じです。よろしくお願いします。

**Comment by Takatatsu9** [comment]
段落から抜けるときは1行以上何も書いて空の行を挟んでくださいね。
そうしないと同じ段落の内容として見えちゃって読み間違えるので・・・

**Comment by konta3291** [comment]
ご回答ありがとうございます。
度重なる質問申し訳ございません。
 - エラーとなってしまった場合の挙動はどういたしましょうか。


ご確認よろしくお願いします。

**Comment by Takatatsu9** [comment]
- どのエラーでも同じ、入力値が不正である旨の文言を表示してください

> 度重なる質問申し訳ございません。

むしろ不明瞭な部分を無くそうという努力が感じられるので好評価ですよ
（何も質問してこないもう一人を見ながら）

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました。
では、
 - エラーとなってしまった場合は入力値が不正である旨を表示し、再度入力を求めればよろしいでしょうか。

ご確認よろしくお願いします。

**Comment by Takatatsu9** [comment]
- その通りです。その際は数値の入力を求める文言を再表示してください。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ご確認したいことは以上です。
お時間をとってしまい申し訳ありませんでした。ありがとうございました。

**Comment by konta3291** [comment]
お世話になっております。
ヒット＆ブローの仕様についてご確認したいことがあり、ご連絡をしております。
ご確認したいことは、下記の現象が起こった際の文言はどういたしましょうか。
 - ゲーム起動後の開始文言
 - ユーザーからの数字入力を求める文言
 - ユーザーからの数字入力が不正であった際の文言
 - ヒット＆ブローの結果を表示する文言
 - ゲームクリア後の文言
 - ゲームクリア後もう一度遊ぶ場合のゲーム開始文言
 - ゲームクリア後も一度遊ばない場合のゲーム終了文言

ご確認したい文言は以上です。

また、アプリ起動から終了するまでの流れはどういたしましょうか。
 - 例）開始→数字入力を求める→ヒット＆ブロー結果表示→クリア→再プレイを聞く→終了

以上です。お忙しいと思いますがご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. ゲーム名を表示するか、あるいは不要です
2. 数値の入力を求めることがわかるならば自由です
3. 数値以外が入力されたことがわかるならば自由です
4. `(ヒット数)ヒット　(ブロー数)ブロー`または`ヒット：(ヒット数)　ブロー：(ブロー数)`のどちらか
5. `4.`の次に正解を当てたことを称える旨のメッセージ（自由）
例：「正解です！おめでとうございます！」等
6. 不要です
7. 不要です

最後のは今の実装のままで良いです

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ではそちらの仕様で作業を進めさせていただきます。
お忙しい中ご回答いただきありがとうございました。

**Comment by konta3291** [comment]
度重なる仕様確認申し訳ありません。
ご確認したい内容は下記の２点です。
 - もう一度遊ぶか聞き、ユーザーからの入力を求める位置はどういたしましょうか。
 - 「もう一度プレイしますか？（Y/N）」の問いにユーザーから受け付ける文字は（大文字、小文字）の制限はどういたしましょうか。

お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
なぜ謝るのでしょうか？顧客が求めるものを作り上げるために仕様を聞くのはそんなに悪いことなんですか？
私はむしろ仕様を聞かずに求めてないものを作り上げるほうが失礼だと思うのですけど。

1. 以下の形式でお願いします。
```
ゲームクリア
もういちど遊ぶ？:（入力を求める）
```
2. 大文字小文字どちらでも受け付けるようにお願いします。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
そのように考えてくださりありがとうございます。何度も聞くのは失礼かと思っておりました。
今後も顧客の求めるものを作れるように質問させていただきます。よろしくお願いします。

かしこまりました、ではそのように作業を進めさせていただきます。
ありがとうございました。

**Comment by Takatatsu9** [comment]
さっきの回答の補足します。`1.`は質問と入力の間の`:`を表示するのが重要です。

**Comment by konta3291** [comment]
かしこまりました、追加します。
