### ISSUE TITLE
答えを見る隠し機能が欲しい

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/HitAndBlow#5]
`ShowAnswer`と入力したら、答えを表示する

**Comment by konta3291** [comment]
お世話になっております。
答えを見る機能を追加するうえでご確認したいことがあり、ご連絡をしております。
ご確認したい内容は下記の通りです。
 - 数字の入力を求められているときに、ShowAnswerを入力した場合の挙動はどういたしましょうか。
 - リプレイを聞かれているときに、ShowAnswerを入力した場合の挙動はどういたしましょうか。
 - ShowAnswerをすべて大文字、すべて小文字、大文字小文字混合で入力された場合の挙動はどういたしましょうか。
 - 答えを表示する文言はどういたしましょうか。
 - 答えを表示後の挙動はどういたしましょうか。例）数字の入力を求める文言を表示する
 - クリアせずに答えを表示後、再度ShowAswerの入力があった場合の挙動はどういたしましょうか。

以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. この機能は数字の入力を求められている場合のみ有効なものです
2. `1.`の理由により、何もしません
3. 大文字小文字完全一致の`ShowAnswer`のみ答えを表示してください
4. 答えとなる数字のみ表示してください
5. 例の通りで、そのまま数字の入力を求める文言を表示してください
6. ちょっと意味がわかりません

**Comment by konta3291** [comment]
ご回答ありがとうございます。
 - クリアせずに答えを表示後、再度ShowAswerの入力があった場合の挙動はどういたしましょうか。

の伝え方が悪く、申し訳ありません。ご確認したかったことは下記のことです。
 - 1ゲームの中でShowAnswerを2回以上入力された時の挙動はどういたしましょうか。

ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
`ShowAnswer`が入力される度に答えを表示してください

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ではご確認した仕様で作業を進めます。
ありがとうございました。
