### ISSUE TITLE
ギブアップ機能

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/HitAndBlow#6]
`giveup`と入力したら、答えを表示してゲームを終了する

**Comment by konta3291** [comment]
お世話になっております。
ギブアップ機能を追加するうえでご確認したいことがあり、ご連絡をしております。
ご確認したい内容は下記の通りです。
 - 数字の入力を求められているときに、giveupを入力した場合の挙動はどういたしましょうか。
 - リプレイを聞かれているときに、giveupを入力した場合の挙動はどういたしましょうか。
 - giveupをすべて大文字、すべて小文字、大文字小文字混合で入力された場合の挙動はどういたしましょうか。
 - 答えを表示する文言はどういたしましょうか。
 - 答えを表示後、終了する文言はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. ギブアップは数字の入力が求められている時にのみ使える機能です。
（というか答え表示もギブアップも数字の入力を求めてる時以外に入力するタイミング無いですけどね）
2. `1.`の理由から以下略
3. 大小混合でも受け付けます。`gIVeuP`と入力してもギブアップできます。
4. `ギブアップしました。正解は「****」でした。`と表示してください。
5. リトライの選択を促してください

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ではご確認した仕様で作業を進めます。
ありがとうございました。
