### ISSUE TITLE
クリアタイム表示機能

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/HitAndBlow#7]
ゲームを開始してからクリアするまでの時間を表示したい

**Comment by konta3291** [comment]
お世話になっております。
クリアタイムを表示する機能を追加するうえでご確認したいことがあり、ご連絡しております。
ご確認したい内容は下記の通りです。
 - 表示する文言はどういたしましょうか。
 - 表示するタイミングはどういたしましょうか。例）クリア直後 or 正解文言の後
 - 開始とは、アプリを起動してからのことでしょうか、または、初めの四桁の整数入力後でしょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. `クリアタイム 分:秒.ミリ秒`でお願いします
2. 手数の次に続けて表示してください
3. プレイ桁数を入力したあとの、数値入力を求めるメッセージが出た瞬間が計測開始地点です

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ではご確認した仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
お世話になっております。
クリアタイム表示機能の仕様について確認したいことがございます。
確認したいことは下記の２点です。
 - クリアタイム表示位置はどういたしましょうか。
 - クリアタイムで表示するミリ秒の桁数はどういたしましょうか。

以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. 手数に続けて表示してください。具体的には右です。
2. 2桁でお願いします。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
手数表示文言とクリアタイム表示文言の間どういたしましょうか。
例）
 - 正解までX手　クリアタイム 分:秒.ミリ秒        　　間に空白を挟む
 - 正解までX手、クリアタイム 分:秒.ミリ秒 　　間に「、」を挟む

ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
下がいいですね。よろしくお願いします。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。
