### ISSUE TITLE
挑戦桁数変更

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/HitAndBlow#8]
ゲーム開始時に、桁数を3〜10桁まで選んで挑戦したい

**Comment by konta3291** [comment]
お世話になっております。
挑戦桁数変更機能を追加するうえでご確認したいことがあり、ご連絡しております。
ご確認したい内容は下記の通りです。
 - コンピュータ側の数字の重複制限はどういたしましょうか。
 - プレイヤーの桁数制限や、重複数字の制限はどういたしましょうか。
 - 文言はどういたしましょうか。
 - 受け付ける入力はどういたしましょうか。例）3~10の数字のみ
 - 受け付けている入力以外の入力があった場合の挙動はどういたしましょうか。
 - ゲームクリア後の挑戦桁数変更文言はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
> ご確認したいことがあり、ご連絡しております

そんな脳内に直接語りかけていますみたいに言われても…（確認したいことがございます。でいい）

1. 変わりありません
2. 変わりありません
3. `挑戦する桁数を入力してください(3〜10):`でお願いします
4. `3.`の通りです
5. H&Bのゲーム中と同じエラーメッセージを表示してください
6. どういう意味でしょうか？

**Comment by konta3291** [comment]
失礼いたしました。今後からは、「確認したいことがございます。」にします。

ご回答ありがとうございます。
伝わりづらい質問申し訳ありません。
 - ゲームクリア後の挑戦桁数変更文言はどういたしましょうか。

の質問で確認したかったことは
- リプレイする際、挑戦桁数変更は再度質問しますか。また、開始時と同じ文言でしょうか。

です。わかりづらい表現をしてしまい申し訳ありません。
ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
なるほど、わかりました。
はい、その通りでお願いします。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ではご確認した仕様で作業を進めます。
ありがとうございました。
