### ISSUE TITLE
正解まで何手かかったか表示する機能

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/HitAndBlow#9]
クリア時に正解するまで何回入力したかの回数を表示したい

**Comment by konta3291** [comment]
お世話になっております。
正解まで何手かかったか表示する機能を追加するうえでご確認したいことがあり、ご連絡をしております。
ご確認したい内容は下記の通りです。
 - 表示する文言はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
以下のような感じでお願いします
```
数字を入力してください:1234
正解です！
正解まで (回数)手
```

**Comment by konta3291** [comment]
ご回答ありがとうございます。
前文も書いていただきとてもわかりやすいです。ありがとうございます。
かしこまりました、ではご確認した仕様で作業を進めます。
ありがとうございました。
